# Generated by Django 4.2 on 2023-05-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='intended_for',
        ),
        migrations.AddField(
            model_name='medicine',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='shelf_life',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.IntegerField(choices=[(1, 'kaszel suchy'), (2, 'kaszel mokry'), (3, 'gorączka'), (4, 'ból gardła'), (5, 'ból'), (6, 'alergia'), (7, 'odporność'), (8, 'katar'), (9, 'oczy'), (10, 'układ pokoarmowy'), (11, 'skaleczenia'), (12, 'ukąszenia owadów'), (13, 'antybiotyk'), (14, 'inne')]),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='taken_continuously',
            field=models.BooleanField(default=False),
        ),
    ]