# Generated by Django 4.2 on 2023-05-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0005_familymember_relationship_familymember_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
