# Generated by Django 4.2 on 2023-05-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0006_delete_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstaidkit',
            name='medicine',
            field=models.ManyToManyField(null=True, to='medicine_app.medicine'),
        ),
    ]
