# Generated by Django 4.2 on 2023-05-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0007_alter_firstaidkit_medicine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyMember',
        ),
    ]
